apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: pruebas
  labels:
    app: graf
spec:
  ports:
    - port: 3000
  selector:
    app: graf
  type: NodePort

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-pvc
  namespace: pruebas
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi   

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: pruebas
  labels:
    app: graf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: graf
    spec:
      containers:
      - image: grafana/grafana
        name: graf
        ports:
        - containerPort: 3000
          name: graf
        volumeMounts:
          - name: graf-vol
            mountPath: /var/lib/grafana
      volumes:
      - name: graf-vol
        persistentVolumeClaim:
          claimName: graf-pvc