apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv1
  namespace: pruebas
spec:
  storageClassName: jenkins-pv1
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/