apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pruebas
  labels:
    app: prom
spec:
  ports:
    - port: 9090
  selector:
    app: prom
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: p-config
  namespace: pruebas
  labels:
    app: prom
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
     - job_name: 'prometheus'
       static_configs:
       - targets: ['localhost:9090']
     - job_name: 'node_exporter_1'
       static_configs:
       - targets: ['192.168.49.2:9100']
     - job_name: 'jenkins'
       metrics_path: /prometheus
       static_configs:
         - targets: ['192.168.49.2:30000x']
---       
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-vol
  namespace: pruebas
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometh-deploy
  namespace: pruebas
  labels:
    app: prom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - image: prom/prometheus
        name: prom
        ports:
        - containerPort: 9090
          name: prom
        volumeMounts:
        - name: p-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prom-vol
          mountPath: /prometheus/data
      volumes:
        - name: p-config
          configMap:
            name: p-config
        - name: prom-vol
          persistentVolumeClaim:
            claimName: prom-vol